"Resource/UI/HudDemomanCharge.res"
{	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"0"
		"xpos_minmode"	"10"
		"ypos"			"0"
		"ypos_minmode"	"0"
		"zpos"			"2"
		"wide"			"79"
		"wide_minmode"	"53"
		"tall"			"8"
		"tall_minmode"	"6"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}					
}
